# Generated by Django 3.2.16 on 2022-11-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='username',
        ),
    ]
